{{- if .Values.backupRestore.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.backupRestore.namePrefix }}-backup-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store
  target:
    name: {{ .Values.backupRestore.namePrefix }}-backup-credentials
    creationPolicy: Owner
  data:
    - secretKey: S3_KEY
      remoteRef:
        key: initial-secret-preset
        property: S3_KEY
    - secretKey: S3_SECRET
      remoteRef:
        key: initial-secret-preset
        property: S3_SECRET
    - secretKey: DISCORD_WEBHOOK
      remoteRef:
        key: initial-secret-preset
        property: DISCORD_WEBHOOK
{{- end }}
