{{- if .Values.backupRestore.enabled }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.backupRestore.namePrefix }}-backup-aip
spec:
  # Run on demand for testing: kubectl create job --from=cronjob/{{ .Values.backupRestore.namePrefix }}-backup {{ .Values.backupRestore.namePrefix }}-backup-manual -n {{ .Values.backupRestore.app.namespace }}
  suspend: {{ .Values.backupRestore.suspendBackup }}
  schedule: "{{ .Values.backupRestore.backupSchedule }}"
  timeZone: "{{ .Values.backupRestore.timeZone | default "UTC" }}"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600
      template:
        spec:
          serviceAccountName: {{ .Values.backupRestore.namePrefix }}-backup-sa
          restartPolicy: OnFailure
          containers:
            - name: app-backup
              image: "pjamenaja/onix-v2-jobs:{{ .Values.onixJobs.imageTag }}"
              imagePullPolicy: IfNotPresent
              command: ["ruby"]
              args: ["app-backup.rb"]
              env:
                - name: DB_POD_NAME
                  value: "postgresql-aip-0"

                - name: APP_POD_KEYWORD
                  value: "onix-legacy-api-aip"
                  
                - name: FILE_PREFIX
                  value: "onix-prod-aip"

                - name: DB_TYPE
                  value: "{{ .Values.backupRestore.db.type }}"
                - name: DB_NAMESPACE
                  value: "{{ .Values.backupRestore.db.namespace }}"
                - name: DB_POD_LABEL
                  value: "{{ .Values.backupRestore.db.podLabel | default "" }}"
                - name: APP_NAMESPACE
                  value: "{{ .Values.backupRestore.app.namespace }}"
                - name: APP_POD_LABEL
                  value: "{{ .Values.backupRestore.app.podLabel | default "" }}"
                - name: APP_DATA_PATH
                  value: "{{ .Values.backupRestore.app.dataPath }}"
                - name: S3_STORAGE_URL
                  value: "{{ .Values.backupRestore.storage.url }}"
                - name: S3_BUCKET
                  value: "{{ .Values.backupRestore.storage.bucket }}"
                - name: S3_BUCKET_PATH
                  value: "{{ .Values.backupRestore.storage.bucketPath }}"
                - name: S3_TRANSFER_TIMEOUT_SEC
                  value: "{{ .Values.backupRestore.s3TransferTimeoutSec | default 1800 }}"
                - name: S3_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.backupRestore.namePrefix }}-backup-credentials
                      key: S3_KEY
                - name: S3_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.backupRestore.namePrefix }}-backup-credentials
                      key: S3_SECRET
                - name: DISCORD_WEBHOOK
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.backupRestore.namePrefix }}-backup-credentials
                      key: DISCORD_WEBHOOK
{{- end }}
