apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: basic-auth-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: basic-auth-secret     # name of the k8s Secret to be created
  data:
  - secretKey: auth
    remoteRef:
      key:  initial-secret-preset
      {{- if eq .Values.envAlias "dev" }}
      property: ONIX_BASIC_AUTH_DEV
      {{- else if eq .Values.envAlias "prod" }}
      property: ONIX_BASIC_AUTH_PROD
      {{- end }}
