kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: onix-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: onix-data-aip
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
